apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nurddnz2e-dotnet-basic-prod
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/nurddnz2e-dotnet-basic/overlays/prod
    repoURL: https://github.com/rhtap-rhdh-qe/nurddnz2e-dotnet-basic-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-prod
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
